=== iesbillenguatges/validarXML/cataleg.dtd
<!ELEMENT cataleg (llibre+)>
<!ELEMENT llibre (titol, autor, any, preu)>
<!ATTLIST llibre categoria (novel·la | assaig | tecnologia) #REQUIRED>
<!ELEMENT titol (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT any (#PCDATA)>
<!ELEMENT preu (#PCDATA)>

=== iesbillenguatges/validarXML/cataleg.xml
<?xml version="1.0"?>
<!DOCTYPE cataleg SYSTEM "cataleg.dtd">
<cataleg>
    <llibre categoria="tecnologia">
    <titol>Aprendre XML</titol>
    <autor>Joan Garcia</autor>
    <any>2023</any>
    <preu>25.50</preu>
</llibre>
<llibre categoria="novel·la">
    <titol>La ciutat perduda</titol>
    <autor>Marta Soler</autor>
    <any>2019</any>
    <preu>18.90</preu>
    </llibre>
</cataleg>
